name: Merge Main into Feature Branches

on:
  push:
    branches:
      - main
    paths: 
      - 'tokens/**'
      - '!.github/workflows/**'

env:
    GIT_PAT: ${{ secrets.GIT_PAT }}    

jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "icellmobilsoft-robot"
          git config --global user.email "68945943+icellmobilsoft-robot@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge tokens directory from main into all feature branches
        run: |
          # Iterate through remote feature branches
          for branch in $(git branch -r | grep -v 'origin/main'); do
            branch_name=$(echo $branch | sed 's|origin/||')  # Remove 'origin/' prefix
            echo "Merging tokens directory from main into $branch_name"
            
            # Check out the remote branch
            git checkout -b $branch_name origin/$branch_name
            
            # Pull the latest changes for the branch to ensure it's up to date
            git pull origin $branch_name
            
            # Copy only the tokens directory from main to the current branch
            git checkout origin/main -- tokens/
            
            # Check if there are any changes to commit
            if [[ $(git status --porcelain) ]]; then
              echo "Changes detected in tokens directory."
              git add tokens/
              git commit -m "Merged tokens directory from main into $branch_name"
              
              # Push changes using PAT for authentication
              git push https://x-access-token:$GIT_PAT@github.com/i-Cell-Mobilsoft-Open-Source/ids-core-ios.git $branch_name || echo "Failed to push $branch_name"
            else
              echo "No changes in tokens directory for $branch_name."
            fi
          done
        